export const SET_USER_PROFILE_EDITED = "SET_USER_PROFILE_EDITED";
export const SET_USER_PROFILE_MODAL_OPEN = "SET_USER_PROFILE_MODAL_OPEN";
export const SET_USER_PROFILE_IMAGE_DATA = "SET_USER_PROFILE_IMAGE_DATA";
export const SET_USER_PROFILE_IMAGE_ERROR = "SET_USER_PROFILE_IMAGE_ERROR";
export const SET_USER_PROFILE_MODAL_READ_ONLY =
  "SET_USER_PROFILE_MODAL_READ_ONLY";
